apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-applications

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prometheus-applications
rules:
- apiGroups: [""]
  resources:
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources:
  - configmaps
  verbs: ["get"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus-applications
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prometheus-applications
subjects:
- kind: ServiceAccount
  name: prometheus-applications